### ISSUE TITLE
Using sensitive user information, Vercel blocks the page

### ISSUE THREAD

**Issue by artistatbl** [dragondevs28/project-manager#1]
An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance, which may provide additional details about the nature of the error.

`session?.user.whateverthisis` wrong
 
import the user detail from prisma 

` const user = await prisma.user.findUnique({
    where: { email: session!.user!.email },
  });
 `
`user.whaterverthisis` right

**Comment by skdrh** [comment]
Where did you face that error?

**Comment by artistatbl** [comment]
The error happens after I login; when I post a project, I click on the view project, which is when it happens.

**Comment by skdrh** [comment]
It's just for testing and using a limited testing database the error you are facing might cause of that, I don't get any errors when I'm testing in production locally.

**Comment by artistatbl** [comment]
Yeah, I had the same problem when I deployed to Vercel, but it worked fine locally but wouldn't work on production builds.

**Comment by skdrh** [comment]
`⨯ PrismaClientInitializationError: 
Invalid `prisma.project.findUnique()` invocation:


Error querying the database: FATAL: too many connections for role "yirimgrb"
    at si.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:125:7117)
    at si.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:125:6151)
    at si.request (/var/task/node_modules/@prisma/client/runtime/library.js:125:5859)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:130:9805)
    at async m (/var/task/.next/server/app/api/projects/route.js:1:821)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
    at async eI.execute (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
    at async eI.handle (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
    at async Y (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:24556)
    at async Q.responseCache.get.routeKind (/var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1025) {
  clientVersion: '5.8.1',
  errorCode: undefined
}` look that's the log as you can see too many connections the database i'm using only allowing 5 connections. it's for one user to just test. that's the reason you are getting random errors i did the same many times.

**Comment by skdrh** [comment]
you got discord bro? let's connect there! this is my discord ID: "drh6275"

**Comment by skdrh** [comment]
I have assign 2 of the projects to you did you get the notifications? I just added the notifications system a day 2 ago, still a lot to do in there but, first just made it worked ;)

**Comment by artistatbl** [comment]
No, I haven't received anything, but I sent you a friend request on Discord.

**Comment by artistatbl** [comment]
Ah, yeah, i have just seen the noticafication
